# fly.toml app configuration file generated for dummy-api-fragrant-dust-9754 on 2025-02-01T22:24:53+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dummy-api-fragrant-dust-9754'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
